Pandas - DataFrame and Series

In [2]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print(f"Series::::::{series}")

Series::::::0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Create Series from dict

data = {'a':1, "b":2}
series_dict = pd.Series(data)
print(f"data::::{series_dict}")

data::::a    1
b    2
dtype: int64

In [5]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
# Dataframe
# create a df from a dict of list

data = {
    'Name': ['Swag', 'John', 'Jack'],
    'Age': [25, 30, 45],
    'City': ['Bhubaneswar', 'New York', 'Chicago']
}

df = pd.DataFrame(data)
print(df)

   Name  Age         City
0  Swag   25  Bhubaneswar
1  John   30     New York
2  Jack   45      Chicago

In [8]:
import numpy as np
np.array(df)

array([['Swag', 25, 'Bhubaneswar'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Chicago']], dtype=object)

In [9]:
# Create a df from list of dict
data = [
    {'Name': 'Swag', 'Age': 32, 'City': 'Bhubaneswar'},
    {'Name': 'John', 'Age': 34, 'City': 'Bhubaneswar'},
    {'Name': 'Jack', 'Age': 32, 'City': 'Bhubaneswar'},
    {'Name': 'Sway', 'Age': 32, 'City': 'Bhubaneswar'},
]
df = pd.DataFrame(data)
print(df)

   Name  Age         City
0  Swag   32  Bhubaneswar
1  John   34  Bhubaneswar
2  Jack   32  Bhubaneswar
3  Sway   32  Bhubaneswar

In [10]:
df['Name']

0    Swag
1    John
2    Jack
3    Sway
Name: Name, dtype: object

In [13]:
df.iloc[0][0]

/var/folders/41/stgqyy6n0x1_4vdlctxlgcpr0000gn/T/ipykernel_22201/2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Swag'

In [18]:
# Data manipulation with df
# Add a new col
df['Salary'] = [1000000, 900000, 800000, 800000]
df
# Remove a col
df.drop('Salary', axis=1, inplace=True)
df

   Name  Age         City
0  Swag   32  Bhubaneswar
1  John   34  Bhubaneswar
2  Jack   32  Bhubaneswar
3  Sway   32  Bhubaneswar

In [19]:
# Add age to col
df['Age'] = df['Age'] + 1

In [20]:
df

   Name  Age         City
0  Swag   33  Bhubaneswar
1  John   35  Bhubaneswar
2  Jack   33  Bhubaneswar
3  Sway   33  Bhubaneswar